### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by aminebizid** [oktadeveloper/okta-angular-sign-in-widget-example#12]
I'm getting this CORS error
localhost/:1 Failed to load https://dev-332541.oktapreview.com/api/v1/sessions/me: Response to preflight request doesn't pass access control check: No '**Access-Control-Allow-Origin' header is present on the requested resource**. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by mraible** [comment]
You need to add http://localhost:4200 as a trusted origin in Okta. Log in to the dev console and go to API > Trusted Origin. I think. Sorry, I'm on my phone. ;)

**Comment by jdk339** [comment]
Still receiving this error after adding the proper URL to Okta.

`/home:1 Failed to load https://dev-00000.oktapreview.com/api/v1/sessions/me: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://aws-website-sw075.s3-website-us-east-1.amazonaws.com' is therefore not allowed access.`

I added the logout redirect URI, but it doesn't seem to work. What's odd is that the logout works on localhost without adding the localhost URL to Okta, but it doesn't work once I publish it to S3.

The code for the logout is:

`logout(): void {
    this.oktaAuthService
      .logout()
      .then(result => {
        this.router.navigateByUrl('/');
      })
      .catch(error => console.error(error));
  }`

**Comment by mraible** [comment]
@jdk339 If you log in to your dev console on Okta and navigate to API > Trusted Origins - is `http://aws-website-sw075.s3-website-us-east-1.amazonaws.com` listed?

**Comment by aminebizid** [comment]
Never trust your JavaScript code in CORS.

**Comment by jdk339** [comment]
@mraible That seems to have fixed it, thanks!

**Comment by mraible** [comment]
@codekousik Can you please post your question to our [Developer Forums](https://devforum.okta.com/)? There will be more Okta folks who can help you there.
