### ISSUE TITLE
Okta SSO page is not coming on clicking the login button in angular 9.

### ISSUE THREAD

**Issue by SarojiOS** [oktadeveloper/okta-angular-sign-in-widget-example#17]
While i am running the okta sample app for angular 9, on clicking of the login button nothing happens. And in the network call i saw openid-configuration fails.
Could you please help me how to solve this issue?

**Comment by mraible** [comment]
If you look in your developer console, do you see any errors there? It's difficult to help when there's no way to reproduce the issue.

**Comment by SarojiOS** [comment]
The openid-configuration api cancelled without any error. I am thinking may be about the proxy. Can you help me if it is proxy then how can i set proxy?

**Comment by mraible** [comment]
If you're behind a proxy, this might help: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/
