### ISSUE TITLE
Requires CORS to be enabled on app

### ISSUE THREAD

**Issue by oldskool73** [oktadeveloper/okta-angular-sign-in-widget-example#2]
Hi, just running through the post and found I couldn't connect to the Okta api from angular due to CORS not being enabled, had to hunt down where this is set (via http://developer.okta.com/docs/api/getting_started/enabling_cors.html) and enable it for the app for it to work. Maybe this should be added to the tutorial?

**Comment by mraible** [comment]
For some reason, I wasn't subscribed to this repo. Sorry about that. I'll get this fixed soon.
