### ISSUE TITLE
Fix for login panel not showing on logout

### ISSUE THREAD

**Issue by oldskool73** [oktadeveloper/okta-angular-sign-in-widget-example#3]
Running through the tutorial I noticed that if you bind to the `hidden` property in the template, instead of using `ngIf`, the panel shows again after a logout, e.g.

```
...
<div [hidden]="user" id="okta-login-container"></div>

<div [hidden]="!user">
...
```

**Comment by mraible** [comment]
Thanks for the tip! I'll update the blog post and close this issue once it's done.

**Comment by mraible** [comment]
I tried this and I still have the same issue - nothing happens when I click the Logout button.

**Comment by mraible** [comment]
Related: https://github.com/okta/okta-signin-widget/issues/247
