### ISSUE TITLE
Use this to consume custom secured API 

### ISSUE THREAD

**Issue by gaurav-sharma** [oktadeveloper/okta-angular-sign-in-widget-example#4]
Using this as the first step, let's say I have a custom REST API that I would like to consume in the Angular app. How do I make authenticated requests to the API? How do I tie API data to the logged in user? For example, if I want all "Foos" that the user has, how would I get them?

In my case, I'm using Spring Boot to create the API but the question is independent of API implementation platform.

**Comment by mraible** [comment]
Here's an example I created that uses Stormpath's SDKs (Java and Angular) to talk to Okta:

https://github.com/mraible/okta-spring-boot-angular-example

Uses OAuth, JWTs, and talks to a Spring Boot-based API.

**Comment by mraible** [comment]
Please see https://developer.okta.com/blog/2017/06/13/add-authentication-angular-pwa for a writeup on how to do this.
