### ISSUE TITLE
 NativePromise.resolve is not a function

### ISSUE THREAD

**Issue by zigzag95** [oktadeveloper/okta-angular-sign-in-widget-example#9]
I get this error when running npm start or ng build

Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
    at desc.set (zone.js:1028)
    at t.exports (okta-sign-in.min.js:13)
    at u (okta-sign-in.min.js:13)
    at Object.<anonymous> (okta-sign-in.min.js:14)
    at e (okta-sign-in.min.js:13)
    at Object.<anonymous> (okta-sign-in.min.js:13)
    at e (okta-sign-in.min.js:13)
    at Object.<anonymous> (okta-sign-in.min.js:13)
    at Object.<anonymous> (okta-sign-in.min.js:13)

**Comment by mraible** [comment]
Can you please provide more details? For example, your version of Node/npm, operating system, version of Angular CLI, etc. I need to be able to reproduce the problem to fix it. ;)

**Comment by RaduGrama** [comment]
Happening to me as well:

@angular/cli: 1.4.4
node: 6.11.2
os: darwin x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4

**Comment by RaduGrama** [comment]
Seems like a known issue: https://github.com/angular/zone.js/issues/891

**Comment by mraible** [comment]
(sigh) Looks like someone broke semantic versioning again. This is why version ranges don't work that great in `package.json`. Please try removing ranges like I did in #10 and see if that helps.

**Comment by RaduGrama** [comment]
Yes, that fixes the issue.

**Comment by aminebizid** [comment]
I think we must keep this issue open since we still use NativePromise. This wont work with angular 5.

**Comment by mraible** [comment]
Feel free to open a new issue for your particular problem. The fix I committed works for this example application. Thanks!

**Comment by Bennyelg** [comment]
Not working for me.

**Comment by mraible** [comment]
It'd be better to open the issue in https://github.com/okta/okta-signin-widget since this project is just an example that uses the Sign-In Widget.

**Comment by mraible** [comment]
Hey everyone: `v2.5.0` of the Sign-In Widget solves this issue. I've upgraded this example. You can see the changes in https://github.com/oktadeveloper/okta-angular-sign-in-widget-example/pull/11.
